### ISSUE TITLE
Add a CLI tool to create new sites and launch them in a local server

### ISSUE THREAD

**Issue by Mcrich23** [twostraws/Ignite#1]
I would love to be able to run the target and it opens `index.html` properly with formatting. Right now, I build it and open it locally and get this:

<img width="1624" alt="Screenshot 2024-03-22 at 1 27 51 PM" src="https://github.com/twostraws/Ignite/assets/81453549/c9f6f48e-810b-48b4-a4d3-40f08709008e">

But running it on a cloudflare site works fine

**Comment by twostraws** [comment]
Most folks are likely to do this using a local web server. The most common was is using Python, which ships with one. `cd` into your Build directory on the command line, then run `python3 -m http.server` to start the server. You should now be able to visit http://localhost:8000 to access your site, rendered normally.

**Comment by Mcrich23** [comment]
Thank you, I figured this out. Might be something to add to the executable to have it built in.

**Comment by twostraws** [comment]
Yes, I agree. This issue should stay open, but I've renamed it to the bigger problem: we need a way to generate new sites quickly, and also run those sites.

**Comment by Mcrich23** [comment]
@twostraws I could write shell scripts to do these things. However, I don't know how to turn this into a cli.

**Comment by Mcrich23** [comment]
@twostraws I have put together a couple shell script to do exactly what it needed but you should probably be the one to publish it. It has 2 commands: 

`ignite create-template [-n|--name new_folder_name] [destination_path]` which fetches the starter repo and unzips it and if you specify a name it will rename IgniteStarter to the name.

and `ignite run [-p|--port] [-d|--directory]` which will startup a server on port 80 and run the package
[Ignite-CLI.zip](https://github.com/twostraws/Ignite/files/14733859/Ignite-CLI.zip)

**Comment by Mcrich23** [comment]
There were some bugs, so I made fixes to the script: 
[Ignite-CLI.zip](https://github.com/twostraws/Ignite/files/14810290/Ignite-CLI.zip)

**Comment by twostraws** [comment]
This is now resolved.
