### ISSUE TITLE
Feature Request: Add capability to make links open their targets in new browser tabs.

### ISSUE THREAD

**Issue by cpah** [twostraws/Ignite#109]
It is often useful to get links to open in a new tab, rather than having the link target replace the currently open page. I currently use Hugo to build my website and I have implemented a default (render-link.html) procedure that, depending on the contents of the <href> string (e.g. the string contains "https"), adds `target="_blank"` to the `href` string.

An example of the use of `target="_blank"` can be seen in this link in one of my _Download on the App Store_ buttons:

```html
<a href="https://apps.apple.com/us/app/macosmoney/id1585329749" target="_blank"><img src="/images/Download_on_the_Mac_App_Store_Badge_US-UK_RGB_blk_092917.svg" /></a>
```

Although I could (and will, if I move to Ignite) simply put the code in the example above into an `Include` file, I have other links (without a button image) that should open their targets in new tabs and it would be onerous to write `Include` files for all of them!

## Proposal

Please consider adding a modifier to, or an (optional?) argument in, the Link() function that forces the link target to open in a new browser tab by appending `target="_blank"` to the target `href` string.

For example:

```swift
Link("Crizzle", target: "https//:crizzle.co.uk")
.linkStyle(.newTab)
```
or

```swift
Link("Crizzle", target: "https//:crizzle.co.uk", mode: "newTab")
```
would result in:

```html
<a href="https://crizzle.co.uk" target="_blank"></a>
```

**Comment by cpah** [comment]
Sorry, Paul. You had already provided this capability. I have just navigated to the _Link.swift_ file in the _Ignite_ package and found the `.target(.blank)` modifier there. I have tested it and it works!

**Comment by twostraws** [comment]
We should add sample code for this to the Ignite Samples repository 👍

**Comment by dl-alexandre** [comment]
Have a [PR](https://github.com/twostraws/IgniteSamples/pull/18) here.
