### ISSUE TITLE
Feature Cursor change on hover

### ISSUE THREAD

**Issue by markstamer** [twostraws/Ignite#112]
### What is missing
In case of using `onClick` instead of a link or button the cursor does not change to a hand to indicate that something is clickable. 

### How we could add it
There seems to be a simple style one could use `.style("cursor: pointer")` to archive this. I can imagine a `Cursor` type and to directly use this as a parameter for the onClick method or just as a modifier like `func cursor(_ cursor: Cursor) -> PageElement`. 

Any thoughts?

**Comment by twostraws** [comment]
I think `func cursor(_ cursor: Cursor) -> PageElement` is exactly correct 👍

**Comment by markstamer** [comment]
All right, will make a PR at times.
