### ISSUE TITLE
Not so much an Issue; more of a warning about the impact of Build folder names on links to other pages.

### ISSUE THREAD

**Issue by cpah** [twostraws/Ignite#117]
When the _Build_ folder is generated by Xcode, the case of the folder names that are created from _Sources/Pages_ files is always set to lower case, whatever the name of the _Sources/Pages_ file's `StaticPage` or `ContactPage` struct. 

For example,
```swift
struct Support: StaticPage {
    var title = "Support"
    ...
}
```
produces a _Build_ subfolder called `support`. If you link to your support page with `[Support](/Support)`, the link may not work. From my experimentation, the link will work on macOS browsers but not on iOS browsers. The link, as you would expect, needs to be changed to match the _Build_ subfolder, i.e. `[Support](/support)`

Furthermore,
```swift
struct RegularServices: StaticPage {
    var title = "RegularServices"
    ...
}
```
produces a _Build_ subfolder called `regular-services`.  Any capitalisation of `StaticPage` or `ContactPage` struct names results in different _Build_ subfolder names. I suggest it would be useful to include a warning note, in any future guidance, for users to check the contents of the _Build_ folder and its subfolder names when creating internal links to _Sources/Pages_ in within Ignite websites.

PS. There is a similar issue with tags. A `macOS` tag produces a `mac-o-s` subfolder in _Build/tags_ subfolder.

**Comment by JPToroDev** [comment]
Please feel free to submit a PR addressing this topic, or open a new issue if you need assistance.
