### ISSUE TITLE
New SwiftUI-style HTML Protocol & Site Environment aren't used when creating new project, and project won't finish running

### ISSUE THREAD

**Issue by B4DG3R** [twostraws/Ignite#144]
Hi All.

I have found 3 issues which I believe may have been caused by the last PR merge (or 2 of them at least).

1. When creating a new `Project` the new `SwiftUI-style HTML Protocol & Site Environment` aren't being used.  The project is still being created with the older style context function headers.  This could cause a lot of confusion for anyone new starting out with ignite.

2. After clearing the errors by updating `HTML` -> `HTMLDocument` & `Body` -> `HTMLBody` etc in line with the new documentation, the `@Page private var Page` property is giving me an error.

```swift
Struct 'Page' cannot be used as an attribute
Type annotation missing in pattern
```

3. The project won't seem to finish building, even in a new test project with nothing in it.  We hit `Build` -> `the project Runs` but it never finishes hence no `Build` folder is created.

While trying to raise evidence for my PR last night my fork `Main` branch was behind the main project and there was a merge conflict so I merged in main to clear the conflicts, and even after clearing all of the errors something isn't right.

If someone could take a loooook I would greatly appreciate it.  I have taken a look although I feel this issue is slightly out of my depth and may be better suited to the person who implemented the change, as I just can't see the issue 😅.

**Comment by gavineadie** [comment]
"This could cause a lot of confusion for anyone new starting out with ignite."

.. it just caused this moderately experienced Ignite a minor fit!  It's too late tonight .. I'll return tomorrow .. Gavin

**Comment by gavineadie** [comment]
Super!  I reappeared at exactly the wrong time!  Good luck with the changes and a happy (US) Thanksgiving
