### ISSUE TITLE
New site generated with `ignite new` command fails to compile

### ISSUE THREAD

**Issue by jazzychad** [twostraws/Ignite#145]
I am checking out Ignite, but the base site generated with `ignite new` (and even the IgniteStarter repo projec) fail to compile due to errors out of the box:

<img width="1098" alt="image" src="https://github.com/user-attachments/assets/7b107c90-ca31-46b7-8e0b-6644a51cddb0">

and

<img width="1098" alt="image" src="https://github.com/user-attachments/assets/289360b5-c40f-40cd-9c06-ee0a0670e913">

As far as I can tell, the `Head` element doesn't even exist anywhere in the repository?

For reference, the errors in text format are:

```
Showing All Errors Only
/tmp/MyIgniteSite/Sources/Pages/Home.swift:7:47: Use of protocol 'BlockElement' as a type must be written 'any BlockElement'

/tmp/MyIgniteSite/Sources/Pages/Home.swift:4:8: Type 'Home' does not conform to protocol 'StaticPage'

/tmp/MyIgniteSite/Sources/Site.swift:20:15: Ambiguous use of 'init(_:)'

/tmp/MyIgniteSite/Sources/Themes/MainTheme.swift:5:60: Use of protocol 'HTML' as a type must be written 'any HTML'

/tmp/MyIgniteSite/Sources/Themes/MainTheme.swift:4:8: Type 'MyTheme' does not conform to protocol 'Theme'
```

**Comment by jazzychad** [comment]
ah, i see that the `ignite new` command literally clones the IgniteStarter repo, so the issue really lies there?

**Comment by kdjanz** [comment]
I solved this issue for myself in the site.swift file by editing the 
var url = URL("...           line to be 
var url:URL  = URL("https://www...
That clarified to the compiler which init I really wanted to use. I think this is a Swift 6 change but I don't really know enough to know.

**Comment by twostraws** [comment]
There are still some big changes going through – the latest is #150. We're doing our best to get everything merged in, then we'll update the docs and sample code ASAP afterwards. Thank you for your continued patience!

**Comment by JPToroDev** [comment]
@jazzychad @kdjanz Over the past couple weeks I've made some substantial PRs that sent Ignite into a rapid growth spurt. Like all growth spurts, it's been accompanied by unavoidable growing pains. @twostraws has been working tirelessly with me behind the scenes to get these changes incorporated as quickly as possible so that the sample docs and example code can be updated with accurate information—and so that the future of building with Ignite can be as enjoyable as possible. We're in the home stretch, and very eager to get everything stable. I'm confident it will be well worth the wait. 😄

**Comment by gavineadie** [comment]
As Paul noted a few days ago on X:

"This means the project will be unstable on main over for a few days – apologies! 
Once everything is landed I'll update the docs, but in the meantime I'd suggest you use the 0.2.2 tag."

**Comment by Celtiore** [comment]
try : var url = URL(filePath: ### "https://www.exemple.com")!

**Comment by JPToroDev** [comment]
These issues have been resolved in the latest batch of changes, and there will soon be an announcement confirming the project's stability.

**Comment by kdjanz** [comment]
When is the new and improved Ignite going to hit the public with great fanfare?

Thanks

Kelly
