### ISSUE TITLE
Included tests fail to build or run

### ISSUE THREAD

**Issue by gavinjerman** [twostraws/Ignite#162]
I want to add a new test to the TextTests class as part of a PR I'm working on to add support for markdown hard line breaks.

Unfortunately when I build the current repository for testing there are 2 compilation errors in the TestSite and TestSubSite files:
<img width="1606" alt="SCR-20241209-khxm" src="https://github.com/user-attachments/assets/5aa41c2a-05e9-4778-864e-b5621aaad1a5">

Commenting out the offending lines raises another compilation error in the Test_customFont method on TextTests:
<img width="1605" alt="SCR-20241209-kims" src="https://github.com/user-attachments/assets/df62c6fb-4cb7-4123-94f0-fc31ac76123d">

Commenting out this test allows the package to build for testing.

However, running Test on the package raises the following error in the ElementTest class:
<img width="1603" alt="SCR-20241209-kjbo" src="https://github.com/user-attachments/assets/6b7ff167-5317-47a7-924c-d75f71750c45">

The same error is raised if I just try run run a single existing test e.g. test_markdownSoftBreaks.

Perhaps the recent slew of 'architectural' commits have broken the existing tests and they're a work in progress?

**Comment by dl-alexandre** [comment]
See PR #132

**Comment by JPToroDev** [comment]
This issue has been resolved with the latest batch of changes.
