### ISSUE TITLE
Call Script("JavaScript") as an Action in a Button

### ISSUE THREAD

**Issue by CreateTheImaginable** [twostraws/Ignite#163]
I did not see a way to do this?

I wanted to to call a JavaScript using the Script element like so...

First I define a simple JavaScript AJAX function.   

            Script("function loadDoc() {
                            const xhttp = new XMLHttpRequest();
                            xhttp.onload = function() {
                               document.getElementById("demo").innerHTML = this.responseText;
                             }
                            xhttp.open("GET", "ajax_info.txt", true);
                            xhttp.send();"
             }

Then try to call the JavaScript AJAX function using an Ignite Button.

            Text {
                Button("Call") {
                    Script("loadDoc()")  // I get an error... Argument type 'Script' does not conform to expected type 'Action'
                }
                    .role(.default)

**Comment by twostraws** [comment]
Yes, that code won't do what you expect. Right now this could be done with a `CustomAction` – something like `CustomAction(code: "loadDoc()") is likely to work. It's not a particularly great name for it, though!
