### ISSUE TITLE
building issues with scope

### ISSUE THREAD

**Issue by eren9677** [twostraws/Ignite#178]
I've just installed ignite and created a new project. however, the ignite build command gives me errors such as : /Documents/Deneme/Sources/Pages/Home.swift:4:14: error: cannot find type 'StaticPage' in scope
 2 | import Ignite
 3 | 
 4 | struct Home: StaticPage {
   |              `- error: cannot find type 'StaticPage' in scope
 5 |     var title = "Home"
 6 | 
[3/8] Compiling IgniteStarter MainTheme.swift
/Documents/GitHub/Deneme/Sources/Themes/MainTheme.swift:5:60: error: use of protocol 'HTML' as a type must be written 'any HTML'
 3 | 
 4 | struct MyTheme: Theme {
 5 |     func render(page: Page, context: PublishingContext) -> HTML {
   |                                                            `- error: use of protocol 'HTML' as a type must be written 'any HTML'
 6 |         HTML {
 7 |             Head(for: page, in: context)

/Documents/GitHub/Deneme/Sources/Themes/MainTheme.swift:4:8: error: type 'MyTheme' does not conform to protocol 'Theme'
 2 | import Ignite
 3 | 
 4 | struct MyTheme: Theme {
   |        `- error: type 'MyTheme' does not conform to protocol 'Theme'
 5 |     func render(page: Page, context: PublishingContext) -> HTML {
 6 |         HTML {

/Documents/GitHub/Deneme/.build/checkouts/Ignite/Sources/Ignite/Themes/Theme.swift:24:9: note: protocol requires property 'name' with type 'String'
 22 | public protocol Theme: Sendable {
 23 |     /// The name of the theme, which must be unique
 24 |     var name: String { get set }
    |         `- note: protocol requires property 'name' with type 'String'
 25 | 
 26 |     /// Primary brand color

/Documents/GitHub/Deneme/Sources/Themes/MainTheme.swift:7:13: error: cannot find 'Head' in scope
 5 |     func render(page: Page, context: PublishingContext) -> HTML {
 6 |         HTML {
 7 |             Head(for: page, in: context)
   |             `- error: cannot find 'Head' in scope
 8 | 
 9 |             Body {

/Documents/GitHub/Deneme/Sources/Themes/MainTheme.swift:9:13: error: cannot find 'Body' in scope
 7 |             Head(for: page, in: context)
 8 | 
 9 |             Body {
   |             `- error: cannot find 'Body' in scope
10 |                 page.body
11 | 

/Documents/GitHub/Deneme/Sources/Themes/MainTheme.swift:6:9: error: 'any HTML' cannot be constructed because it has no accessible initializers
 4 | struct MyTheme: Theme {
 5 |     func render(page: Page, context: PublishingContext) -> HTML {
 6 |         HTML {
   |         `- error: 'any HTML' cannot be constructed because it has no accessible initializers
 7 |             Head(for: page, in: context)
 8 | 

/Documents/GitHub/Deneme/Sources/Themes/MainTheme.swift:6:9: error: use of protocol 'HTML' as a type must be written 'any HTML'
 4 | struct MyTheme: Theme {
 5 |     func render(page: Page, context: PublishingContext) -> HTML {
 6 |         HTML {
   |         `- error: use of protocol 'HTML' as a type must be written 'any HTML'
 7 |             Head(for: page, in: context)
 8 | 
error: emit-module command failed with exit code 1 (use -v to see invocation)
[4/8] Emitting module IgniteStarter
/Documents/GitHub/Deneme/Sources/Pages/Home.swift:7:47: error: cannot find type 'BlockElement' in scope
 5 |     var title = "Home"
 6 | 
 7 |     func body(context: PublishingContext) -> [BlockElement] {
   |                                               `- error: cannot find type 'BlockElement' in scope
 8 |         Text("Hello world!")
 9 |             .font(.title1)

I opened the package with xcode and the Site file had problems too : 
Type 'ExampleSite' does not conform to protocol 'Site'  and 'init(_:)' was deprecated in macOS 13.0: replaced by 'init(filePath:)' 

I changed product destination to my mac but it didn't work. 

I am using Version 16.2 (16C5032a)

**Comment by twostraws** [comment]
We're in the final stages of making some significant updates; this will be resolved soon. Thank you for your patience!
