### ISSUE TITLE
Feature Request: Markdown Parser via Plugin? Alternative, a block that takes a "HTMLRepresentable"

### ISSUE THREAD

**Issue by carlynorama** [twostraws/Ignite#24]
It would be nice to have the Markdown parsed via a "MarkdownParserService" or some patches of  HTML provided by an "HTMLProvider" protocol? 

Perhaps that could even not be a site wide call? My "Recipes" Content folder could use the RecipeoParser package and "BandReviews" could use the MetalMarkerExtreme package... 

Maybe the simplest would be a Block Element that would take in any  "HTMLRepresentable", not just an already rendered include. 

I currently use hugo (partially to keep myself from fussing), but I really miss the plugin architecture of WordPress. hugo's lack of plugins is why I'll probably move on.  Maybe to Ignite!  Thank you!

**Comment by twostraws** [comment]
Understood – that makes perfect sense. So perhaps if I declare a protocol that requires Markdown parsers to accept either a URL or some Markdown string, make it default to the current Markdown parser, then allow developers to override it at the site and/or `ContentPage` level. Would that solve your problem fully?

**Comment by carlynorama** [comment]
I think it might! WooHoo!

**Comment by twostraws** [comment]
This is resolved, although perhaps not as fully as you might have hoped 😅

You can now adjust the Markdown renderer to use site-wide for rendering Markdown placed into the Content folder. This does *not* change the parser used for rendering inline Markdown, e.g. when using `Text(markdown:)`, and I'm afraid there's no option to customize this at the `ContentPage` level – it's one setting for the entire site. Hopefully that's good enough!
