### ISSUE TITLE
URL.packageDirectory(from file:) runs into an infinte loop if it can't find Package.swift anywhere

### ISSUE THREAD

**Issue by dirk68-fu** [twostraws/Ignite#27]
If the extension `URL.packageDirectory(from file:)` can't find a file Package.swift in any parent directory it runs into an infinite loop. Hanging the whole publishing process before it even startet.

**Comment by twostraws** [comment]
Sorry about that! Would you like to contribute or a fix, or would you prefer that I create one?

**Comment by dirk68-fu** [comment]
Hi Paul, Thank you for your great work in the Swift community.
I just started trying out Ignite and do not feel confident enough yet to supply a fix for the issue.

**Comment by twostraws** [comment]
That's okay! I've put it on my todo list and will get it done 👍

**Comment by twostraws** [comment]
Hmm… I'm wondering whether there's a very specific situation that triggers this – it seems to correctly bail out once the path has been searched extensively. Can you trace the problem through on your end and see what the flow is? From what I can see, the loop should exit when `while currentURL.path().isEmpty == false` fails.

**Comment by dirk68-fu** [comment]
Hi Paul.
I tried using Ignite with an Xcode project (template: command line tool). So there was no Package.swift and I remember that the path was never empty, it got longer and longer (multiple GB after running for some seconds) containing all „`../../../.. ...`" at the beginning. Perhaps Xcode compiles pathes into the binary starting with "`../`" ?

**Comment by piotrekjeremicz** [comment]
Paul @twostraws, I found this bug during `PublishingContext.empty` implementation. I am not sure what was wrong, but commit presents two changes in the `PublishingContextKey`:

`32. var url = URL("")` _changed to_
`32. var url = URL("https://example.com")`

and

`49. PublishingContext(for: EmptySite(), from: "")` _changed to_
`49. try! PublishingContext(for: EmptySite(), rootURL: URL.documentsDirectory).`

Maybe this second line had something to do with it.

**Comment by dirk68-fu** [comment]
The problem seems to be that URL.packageDirectory(from file:) searches upwards for Package.swift and breaking the loop if it finds it or id the search path is empty. But it never gets empty after "/" as shown above.

**Comment by alexito4** [comment]
FYI this was fixed by https://github.com/twostraws/Ignite/pull/119

**Comment by twostraws** [comment]
Thank you!
