### ISSUE TITLE
How To Deploy Ignite Website

### ISSUE THREAD

**Issue by mergesort** [twostraws/Ignite#34]
Hey @twostraws, thank you so much for such a great looking library, I've been playing around with it today in earnest and hoping to use it for building a couple of static websites!

I was trying to figure out the best way to deploy a website built with Ignite and didn't see any instructions so I decided to take the [IgniteSamples](https://github.com/twostraws/IgniteSamples) project and use it's Build folder as a baseline for testing. I uploaded the folder directly to Cloudflare Pages (which serves static websites), including everything inside like the index.html, feed.rss, and all of the subdirectories to see if the process was that simple.

Unfortunately the result was a website that wouldn't load, and I still am not sure how to deploy an Ignite site. It's quite possible that I'm doing something incorrectly so I was wondering if you could perhaps share some advice or documentation on the matter?

Thank you again, looking forward to playing more with Ignite!

**Comment by mergesort** [comment]
Welp, nevermind. I swear that minutes after I finished writing this issue the Cloudflare page started loading — I'm guessing it was DNS propagation. There still might be a better way to do this (though I suspect the answer is configure auto-deploys with git and specifying Ignite's Build folder as the website's build folder), but either way sorry to bother you!

**Comment by Mcrich23** [comment]
I managed to setup github actions deploy for my ignite site. You can find it [here](https://github.com/IndieDevAwards/Website)

**Comment by twostraws** [comment]
Issues that resolved themselves are my favorite 🙂   

That being said, I think there's a lot of scope to expand the Ignite CLI tool to include some kind of deployment system in there; I'm not sure if there's a pre-written tool or framework we can lean on there, but it would be nice.

**Comment by mergesort** [comment]
@Mcrich23 Thank you for the great resource, I'll definitely be yoinking that for my website.
@twostraws I'll never say no to more documentation or built in support, would absolutely love that. 🙂
