### ISSUE TITLE
Feature Request:  Card Content Text Positions 

### ISSUE THREAD

**Issue by NigelGee** [twostraws/Ignite#39]
At the moment it can put the text `.bottom`, `.top`, `.overlay` (plus recent added `.overlayCenter`).

Could it have the text `.trailing` and `.leading` (which would snap to `.bottom` if `.trailing` and `.top` if `.leading` when size get too small).

This could also have alignment for the text to be in the top, center, or bottom  of the image.

```
Card(imageName: "/images/rug.jpg") {
    Text(placeholderLength: 100)
}
.contentPosition(.trailing(alignment: .top)
```

**Comment by NigelGee** [comment]
<img width="1055" alt="Screenshot 2024-04-30 at 21 24 46" src="https://github.com/twostraws/Ignite/assets/41487836/4f293965-add4-440a-b8a2-a5a5ab036438">

**Comment by markstamer** [comment]
For now you could try to use a Section within the cards content. Does something like this work for you? 

```swift
Card {
    Section {
        Image("/images/rug.jpg")
        Text(placeholderLength: 100)
    }
}
```

**Comment by JPToroDev** [comment]
Custom cards can now be easily created using the updated API. If you would like to see further improvements to `Card` in particular, feel free to submit a new issue.
