### ISSUE TITLE
Question: How to remove `<div class="col-sm-10...">...</div>` from `Body`

### ISSUE THREAD

**Issue by henrikac** [twostraws/Ignite#41]
I'm trying to add a custom footer to my pages that spans 100% of the width of the screen. This has turned out to be more difficult than I'd expect because the `Body` by default adds a `<div class="col-sm-...">...</div>` around all of its content.

How can I remove this div from the body?

**Comment by twostraws** [comment]
The `Site` protocol has a default value for `pageWidth` of 10. If you want it to span the full width of the screen, override that in whatever type you can conforming too `Site`, e.g.: 

```swift
struct MySite: Site {
   // ...
   var pageWidth = 12
}
```

**Comment by henrikac** [comment]
Thank you for the quick response! Works perfectly!

**Comment by Abbas-Hameed** [comment]
pageWidth  is no longer exist, how can we make it full width now?
