### ISSUE TITLE
Incorrect Var in ExampleSite struct

### ISSUE THREAD

**Issue by StewartLynch** [twostraws/Ignite#44]
The ExampleSite struct incorrectly uses 
`var baseTitle = " - My Awesome Site"`
it should be 
`var titleSuffix = "- My Awesome Site"`

**Comment by twostraws** [comment]
My thinking here was that a page title of "Hello, world" should become "Hello, world – My Awesome Site", hence the leading space.

**Comment by StewartLynch** [comment]
That isn't what I am referring to Paul. When the sample site gets created, the ExampleSite struct uses baseTitle, when in fact is thoiuld be titleSuffix.  There is no baseTitle from what I could see.

**Comment by twostraws** [comment]
Ah! Sorry, without context I couldn't tell. I bet that would explain why it doesn't work on the sample site 😅  Do you want to open a PR, or would you prefer that I do it?

**Comment by twostraws** [comment]
This has been resolved over in the IgniteSamples repository. Thank you!
