### ISSUE TITLE
Question: How to add Font Awesome Support in <head>

### ISSUE THREAD

**Issue by TheArchitectLabs** [twostraws/Ignite#47]
I like to utilize FA in my site. However, the instructions for use are to copy this code into the <head>:  <script src="https://kit.fontawesome.com/xxxxxxxxxx.js" crossorigin="anonymous"></script>

How can I add this to the <head>? I don't see a way to modify that element.

Thank you for the wonderful work on this and I apologize if there is a simple fix that I am just missing.

**Comment by twostraws** [comment]
Right now `Ignite` provides two options for headers:

1. You can build your own from scratch, using `Script` in this case to get the effect you want.
2. You can use the standard headers.

On a live stream about Ignite I mentioned that really we needed some sort of middle ground: "give me all the standard headers, then add these extras…" I'm afraid that isn't currently a thing, but I think this issue is a good reminder that it is needed.

**Comment by pd95** [comment]
I remember the discussion during the live stream. I would volunteer to develop a solution for this, but currently I'm still an "`Ignite` newbie". So I'm wondering what the right approach is to implement it. Here follows my current understanding of the problem:

To include some additional CSS or JS Script file to the website (=every page) one has to to modify the `MyTheme` source which renders the HTML of a page. By default, the content of the <head> tags is created by the call to `Head(for: page, in: context)`. This results in the rendering of the standard headers as they are defined in the `Head` initializer.

To add the additional CSS (using `MetaLink(href: "/css/custom.css", rel: "stylesheet")`) or JS file (using `Script(file: "/js/custom.js")`) we have to use the other initializer (based on `@HeadElementBuilder`), which forces us to copy the standard headers and add our customizations at the end:
```swift
Head() {
    MetaTag.utf8
    MetaTag.flexibleViewport

    if page.description.isEmpty == false {
        MetaTag(name: "description", content: page.description)
    }

    if context.site.author.isEmpty == false {
        MetaTag(name: "author", content: context.site.author)
    }

    MetaTag.generator

    Title(page.title)

    MetaLink.standardCSS

    if context.site.syntaxHighlighters.isEmpty == false {
        MetaLink.syntaxHighlightingCSS
    }

    if context.site.builtInIconsEnabled {
        MetaLink.iconCSS
    }

    MetaLink(href: page.url, rel: "canonical")

    if let favicon = context.site.favicon {
        MetaLink(href: favicon, rel: .icon)
    }

    // Additional headers
    MetaLink(href: "/css/custom.css", rel: "stylesheet")
    Script(file: "/js/custom.js")
}
```

An enhanced API could look as below:
```swift
Head(for: page, in: context) {
    MetaLink(href: "/css/custom.css", rel: "stylesheet")
    Script(file: "/js/custom.js")
}
```

This would could be done by enhancing the current initializer with a parameter `additionalItems` as shown below:
```swift
init(for page: Page, in context: PublishingContext, @HeadElementBuilder additionalItems: () -> [HeadElement])
```

What do you think? Should I prepare a PR with this small enhancement?

**Comment by twostraws** [comment]
Yes, that's exactly correct – add all the standard headers, then let them add any extra ones they want. At some point in the future we could perhaps revisit this to think about removing/replacing headers too to avoid duplicates, but that's definitely for a future release. Thank you!

**Comment by pd95** [comment]
Ok, I've prepared above PR #48.

Based on the proposed solution, the addition of the <script> tag to the <head> could be done like shown below:

```swift
Head(for: page, in: context) {
    Script(file: "https://kit.fontawesome.com/xxxxxxxxxx.js")
        .addCustomAttribute(name: "crossorigin", value: "anonymous")
}
```

**Comment by twostraws** [comment]
I believe this is now resolved fully by @pd95's PR. If you need something further, please open a fresh issue. Thank you!
