### ISSUE TITLE
Question: Dynamic rendering of content using Server Side Swift / Ignite / Vapor ?

### ISSUE THREAD

**Issue by vade** [twostraws/Ignite#58]
Hi

Im playing a bit of catch up here with Ignite but its an exciting project!

I am curious - is there a potential world where Vapor could serve dynamic web content using Ignite as the HTML rendering on the back end? So rather than serving statically rendered HTML, a Vapor end point could serve dynamically rendered Ignite HTML using its syntax?

Just curious, and there isnt a discussion tab here, so apologies for making an issue.

**Comment by twostraws** [comment]
Yes, of course there's potential to do that in the future if needed. It's not planned right now, but it wouldn't be terrifically hard to implement.
