### ISSUE TITLE
Feature request: Blurs and Material support

### ISSUE THREAD

**Issue by Terabyte1385** [twostraws/Ignite#66]
A neat little feature, especially for the navigation bar, would be a `Blur` element or a SwiftUI `Material` port to Ignite. Like in SwiftUI, where a background can be chosen as `Material` and then pick a blur of a special thickness, it would be neat for Ignite to have such element, possibly integrated directly into `.background` as well.

**Comment by Terabyte1385** [comment]
For anyone looking for an implementation with CSS, do this:
`.style("backdrop-filter: blur(20px);")`

**Comment by twostraws** [comment]
While I'm not against the idea, it looks like Safari doesn't support this as a base CSS style at this time, and instead requires prefixing. That makes me wary.

**Comment by JPToroDev** [comment]
This feature has been added in the most recent changes. 🙌🏼
