### ISSUE TITLE
Feature Request: Mobile Optimization

### ISSUE THREAD

**Issue by Mcrich23** [twostraws/Ignite#7]
I am looking at the sites on mobile and the header is NavBar is covering the top on the page content:

![image](https://github.com/twostraws/Ignite/assets/81453549/0d86a48b-56e0-4f0a-8cc8-761f50b614b8)![image](https://github.com/twostraws/Ignite/assets/81453549/0fc34da4-7426-4523-b36f-263285ed5415)

**Comment by Mcrich23** [comment]
Maybe add access to the width of the page via `@Environment`?

**Comment by fbartho** [comment]
@Mcrich23 `@Environment` will be a *build-time* value provider (this is a static site generator). Runtime logic must be embedded in CSS or JS, as Swift isn’t running when the browser loads the page.

**Comment by Mcrich23** [comment]
I understand, I meant `@Environment` or something else would be used and then on compile, it would set css for elements using it.

**Comment by twostraws** [comment]
I have adjusted the IgniteSamples repository to provide an example of how this can be solved with CSS: https://github.com/twostraws/IgniteSamples/blob/414fe428a74e92227012c31d77dab9b2a1742830/Sources/Components/NavBar.swift#L14

That should resolve this issue fully, so I'm to close it. However, if you still have problems please re-open!
