### ISSUE TITLE
Feature Request: Custom font support

### ISSUE THREAD

**Issue by Terabyte1385** [twostraws/Ignite#70]
I tried using a custom font on my website, and then I encountered issues. I'd be awesome to have something like `var robotsConfiguration = Robots()` but for fonts, and then a `Font()` object.

I was able to get it working by CSS, adding a `.style` to the `Theme()` and then another `.style` on the text I want to change the font, but it's not an ideal solution, clearly a workaround.

**Comment by twostraws** [comment]
Great idea! One helpful thing you could do would be to give us an example of what kind of API you'd like to see here? Just fantasyland stuff – if the API were ideal for you, what would it look like? I'm not saying we can make it happen, but it would give us a good starting point 🙂

**Comment by Terabyte1385** [comment]
Hey, thanks for getting back! 

I'm imagining an implementation similar to `Robots()` but I would make a few changes. I'm thinking of something like this:

```
import Foundation
import Ignite

struct CustomFont {
    var familyName: String
    var weight: Font.Weight? = .regular
    var typeface: String? = "sans-serif"
    var location: String? // required for custom locations of the fonts
}

enum CustomFontElement {
    case .spaceMonoBold = CustomFont(familyName: "Space Mono", weight: .bold, location: "https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap")
    // ...
}

struct MyCustomFonts: CustomFontsConfiguration {
    var fonts: [CustomFontElement]
}
```

In Site.swift, we add:
`var customFontsConfiguration = MyCustomFonts()`

And finally, when we want to use one of our custom fonts, we do:
```
Text("The quick brown fox jumps over the lazy dog")
    .font(MyCustomFonts.spaceMonoBold)
```
... or ...
```
Text("The quick brown fox jumps over the lazy dog")
    .font(CustomFont(familyName: "SF Pro Display", weight: .regular, location: "/resources/sf_pro_display_regular.ttf"))
```
By doing this, we not only centralise all the custom fonts, but we can also detect when a font is needed or not and decide whether to load it.

I imagine this is tough. There is a lot to take into consideration: convenience of the developer, where the fonts are stored, what if the fonts are renamed, what happens when a font with a specific style or weight is overwritten by `.fontWeight`, and many others to take into consideration. Now that I found a workaround it's not mission-critical but it would be convenient.

P.S. Please don't judge the code too hard, it's actually one of my first contributions to such a project! I don't have much experience but I'm happy to give a hand!

**Comment by twostraws** [comment]
Zero judgement! Thank you for taking the time to spec things out nicely! I don't know where the final implementation will end up or how long it will take, but at least now we have a starting point 🙌

**Comment by jpurnell** [comment]
@Terabyte1385 can you show how you implemented this as a workaround in your existing site?

**Comment by Terabyte1385** [comment]
> @Terabyte1385 can you show how you implemented this as a workaround in your existing site?

Using CSS via `.style`:

```swift
Text("This text is in Space Mono")
    .font(.title1)
    .style("font-family: 'SpaceMono-Bold', sans-serif;")
```

In the `Theme` you want to do this you must also add:

```swift
.style("""
@font-face {
      font-family: 'SpaceMono-Bold';
      src: url('/fonts/SpaceMono-Bold.ttf') format('truetype');
}
""")
```
Make sure to change the path of the font to wherever you are putting your font file in your project.

**Comment by kdubroff** [comment]
As far as current workarounds, I found I can change the default font-family by applying 2 style elements to `Body`. For some reason, attempting to do both `@font-face` and `font-family: My Custom Font;' in the same `style` block doesn't work.

Working:
```swift
            .style("""
            @font-face {
                font-family: 'EB Garamond';
                src: url('https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap') 
            }
        """)
            .style("font-family: EB Garamond;")
```

I'm also stumped as to why I can't apply the font-family conditionally on tags such as `h1`. I.e. `.style("h1 { font-family: foo;" }` doesn't apply the style to h1 elements. Nor does overwriting `--bs-body-font-family`.

**Comment by froggomad** [comment]
As far as current workarounds, I found I can change the default font-family by applying 2 style elements to `Body`. For some reason, attempting to do both `@font-face` and `font-family: My Custom Font;'` in the same `style` block doesn't work.

Working:
```swift
            .style("""
            @font-face {
                font-family: 'EB Garamond';
                src: url('https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap') 
            }
        """)
            .style("font-family: EB Garamond;")
```

I'm also stumped as to why I can't apply the font-family conditionally on tags such as `h1`. I.e. `.style("h1 { font-family: foo;" }` doesn't apply the style to h1 elements. Nor does overwriting `--bs-body-font-family`.

**Comment by JPToroDev** [comment]
Custom font support has been added in the recent changes to Ignite! If you'd like to see further improvements, please open a new issue or submit a PR with your desired feature. 🙌🏼
