### ISSUE TITLE
Swift 6 build fails

### ISSUE THREAD

**Issue by multitudes** [twostraws/Ignite#81]
I thought this is interesting. It doesn't find the `URL` extension when compiling with the Swift 6 keychain.
The output is:
```
Building for debugging...
[0/5] Write sources
[1/5] Write swift-version-6A63A117629E05AE.txt
error: emit-module command failed with exit code 1 (use -v to see invocation)
[3/7] Emitting module IgniteStarter
/Users/laurentb/Developer/Ignite/ExampleSite/Sources/Site.swift:20:15: error: ambiguous use of 'init(_:)'
18 |     var name = "Hello World"
19 |     var titleSuffix = "My Awesome Site"
20 |     var url = URL("https://www.example.com")
   |               `- error: ambiguous use of 'init(_:)'
21 |     var builtInIconsEnabled = true
```

Swift 5.10 has no problem with it!

**Comment by twostraws** [comment]
It's not ideal, but we could change this. I'm really curious what's causing the breakage here!

**Comment by clarkezone** [comment]
I'm hitting this issue also

**Comment by Rspoon3** [comment]
Still an issue with Version 16.0 beta 6 (16A5230g).

**Comment by ppporch** [comment]
Xcode Version 16.0 beta 6 (16A5230g) has an issue with var url: URL = URL(static: "https://www.example.com"). I get an error message of extraneous argument label 'static:' in call. To fix, remove static:

URL = URL("https://www.example.com") works

**Comment by appfrosch** [comment]
> This should work now in Swift 6, tested with `swift:6.0`

You mean without having to change anything? If so, how–cause I just started looking into Ignite yesterday and had this error as well without any code changes after creating a new site with `ignite new MeWebsite`, using the latest Xcode Version 16.0 (16A242d) …

I also tried to change the Package to this without success:
```swift
// swift-tools-version: 6.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "IgniteStarter",
    platforms: [.macOS(.v13)],
    dependencies: [
        .package(url: "https://github.com/twostraws/Ignite.git", branch: "main")
    ],
    targets: [
        .executableTarget(
            name: "IgniteStarter",
            dependencies: ["Ignite"]),
    ],
    swiftLanguageModes: [.v6]
)

```

I got around this by changing the line to `var url: URL = URL("https://www.example.com")` (as stated in this issue thread).

**Comment by JPToroDev** [comment]
This issue should be resolved now. Feel free to open another one if it resurfaces.
