### ISSUE TITLE
Getting warnings about swift-driver

### ISSUE THREAD

**Issue by clarkezone** [twostraws/Ignite#84]
I have a clean Mac with Xcode 16 Beta 2 on MacOS18 Beta 2, tried following the instructions to build and run ignite and got a bunch of warning about swift-driver which I've not come across before.  I didn't see reference to this in the readme (appols if I missed it) but unclear if this is something I need to install.  Haven't yet had a chance to test this on Linux to see if it is a Mac thing or a general thing.  Might be worth addressing this in the readme.  I'm also hitting build issues which are being addressed in another thread but wanted to file this anyway.

```bash
warning: 'ignite': <unknown>:0: warning: using (deprecated) legacy driver, Swift installation does not contain swift-driver at: '/Library/Developer/CommandLineTools/usr/bin/swift-driver-new'
warning: 'swift-argument-parser': <unknown>:0: warning: using (deprecated) legacy driver, Swift installation does not contain swift-driver at: '/Library/Developer/CommandLineTools/usr/bin/swift-driver-new'
warning: 'swift-markdown': <unknown>:0: warning: using (deprecated) legacy driver, Swift installation does not contain swift-driver at: '/Library/Developer/CommandLineTools/usr/bin/swift-driver-new'
warning: 'swift-cmark': <unknown>:0: warning: using (deprecated) legacy driver, Swift installation does not contain swift-driver at: '/Library/Developer/CommandLineTools/usr/bin/swift-driver-new'
```

**Comment by JPToroDev** [comment]
If you're still encountering this problem, feel free to open a new issue.
