### ISSUE TITLE
Question: supporting alternative css frameworks, such as tailwindcss

### ISSUE THREAD

**Issue by electricsidecar-dev** [twostraws/Ignite#87]
Love the principles behind Ignite and excited to start using + hopefully contributing to it in some form.

My existing site is built using [tailwindcss](https://tailwindcss.com), which I've been really enjoying as an alternative to bootstrap for its point-of-use simplicity. In some ways I feel it's similar to SwiftUI, in that you're encouraged to attach styles to elements inline rather than building a centralized stylesheet.

The reason I want to start using Ignite is that I have a lot of content that I'd like to share between my application and my website, e.g. the app's [Shorcuts documentation](https://electricsidecar.app/shortcuts/), and I'd love for my site to build in the same toolchain as my app so that I can be sure that my site's documentation always reflects the latest app state.

Before I dive too deep into the rabbit hole though, I wanted to pose the question here in case there's some guidance I can follow for exploring use of tailwindcss with Ignite? Am I holding the tool wrong to think that I should try to incorporate tailwindcss or ideas from it?

**Comment by electricsidecar-dev** [comment]
Thinking aloud, I'm considering whether it makes sense to add tailwindcss' css builder as a post-build step to the Ignite site generator.

My current workflow is:

1. Start `npx tailwindcss -i ./.src/main.css -o ./css/main.css --watch` to watch for local changes.
1. Edit static .html files, adding inline `class` annotations as needed to style the site. The site's main.css file is recompiled automatically with each change.
1. Once I've finished my edits, I stop the `tailwindcss` daemon and run `npx tailwindcss -i ./.src/main.css -o ./css/main.css --minify` and then push the generated content to my `main` branch on GitHub, which auto-deploys to GitHub Pages.

This new workflow would be basically the same, but in step 2 I'd use Ignite to edit and generate the static .html files.

**Comment by twostraws** [comment]
I'm afraid this isn't something I'm familiar with, so I can't really help. Although I know Tailwind is very popular, Bootstrap was chosen because of the range of complex controls it comes with, and also the excellent support for accessibility through things such as VoiceOver. If there are ways to make Tailwind support easier, a PR would be welcomed.

**Comment by sanderjson** [comment]
As a theme author my first thought was "Can I use tailwindcss?" However, I found this project from [this video](https://www.youtube.com/watch?v=JJGLoo3A2uk) and it appears that the project purpose is to emulate SwiftUI development (with components pre-designed). Tailwindcss is a utility first CSS library so this approach does not match directly. However, you might be interested in is porting TailwindUI (paid) or some other pre-designed CSS UI framework (Daisy, Shad, other).
