### ISSUE TITLE
Simple line breaks in markdown or using `Text()`

### ISSUE THREAD

**Issue by markstamer** [twostraws/Ignite#91]
It seems that line breaks are ignored in markdown. This is all rendered inline:

```swift
Text(markdown: """
Sollicitudin Etiam
Etiam Sem 42
12345 Purus 
""")
```

Also it would be great to have simple line breaks that don't introduce space between two lines to work, e.g. by ending a line with a backslash. I couldn't achieve this with `Text` either, e.g. by putting multiple text elements in a  `Group`. It would be great for something like displaying an address.

**Comment by henrikac** [comment]
Not sure if you have tried this but try end lines with two or more spaces.

[Markdown Guide - Line Break Best Practices](https://www.markdownguide.org/basic-syntax/#line-break-best-practices)

**Comment by markstamer** [comment]
Thanks for your comment but it doesn't work either. I have "Automatically trimming trailing whitespace" in Xcode enabled but turning it off didn't work either.

**Comment by cpah** [comment]
There is a simple workaround. Xcode's markdown parser supports inline HTML. Add `<br>` at the end of each line. If you want a paragraph-style double space between lines, use `<br><br>`

```swift
Text(markdown: """
Sollicitudin Etiam<br>
Etiam Sem 42<br>
12345 Purus 
""")
```

**Comment by markstamer** [comment]
Awesome, it works. Thanks @cpah I wonder if there is a reason why this does not work out of the box and what the best approach would be to make it work. Either on Swift Markdown parser level or even Ignite.

**Comment by nicosql** [comment]
> Awesome, it works. Thanks @cpah I wonder if there is a reason why this does not work out of the box and what the best approach would be to make it work. Either on Swift Markdown parser level or even Ignite.

The solution is to not use Markdown as there is STILL no true standard hence annoyances like this.  The real solution is to use AsciiDoc.  Superior & standardized and you can bring your Markdown knowledge with you as the most popular compiler also supports Markdown/HTML/docBook/PDF/ePub - ref: AsciiDoctor.   AsciiDocFX is a great and free multi-plat editor or just use a plugin.

**Comment by twostraws** [comment]
PR #138 modified the Markdown parsing to respect soft line breaks. @markstamer / @cpah: Did this help?

**Comment by JPToroDev** [comment]
It appears this problem has been resolved. If not, feel free to open another issue.
