### ISSUE TITLE
Potential Workflow Improving Changes

### ISSUE THREAD

**Issue by mergesort** [twostraws/Ignite#96]
Hi @twostraws, I'm finally actually starting to use Ignite was wondering if there were ways to improve the workflow.

1. Is there a hot-reloading option for ignite that I'm missing, even if it means an automated way to stop and restart the server? I would like the ability to make changes, hit save, and then see the changes reflected on the website I'm building.

2. Have you considered building a SPM plugin that would allow users to build (and perhaps run) directly from Xcode? I would really love to have a workflow where I don't need to pop into the terminal to make changes. If not I can look into this, though admittedly tooling isn't exactly a strength of mine.

3. Is there anything else you do in your personal usage of Ignite that may be beneficial for me to know as a developer dipping my toes into Ignite?

Thank you as always for the framework, and for building a really interesting static site option!

**Comment by twostraws** [comment]
Hello! This is just a quick message to apologize for taking so long to get to this – I'm really overloaded with the after effects of moving house! I'll get to it all this week, for sure. Thank you for your patience!

**Comment by 0xTim** [comment]
@mergesort as an FYI you can just run the project (or `swift run`) to regenerate the site, not ignite CLI needed

**Comment by mergesort** [comment]
Oh thanks @0xTim, that's good to know!

**Comment by cpah** [comment]
There is a workaround, I believe, but it will cost you £9.99. Download _WorldWideWeb - desktop_ from the [Mac App Store](https://apps.apple.com/gb/app/worldwideweb-desktop/id1621370168?mt=12). Create your website in Xcode and run your Package. Load your Build folder into _WorldWideWeb_ and launch _WorldWideWeb_'s  browser. Whenever you update your site in Xcode and run your Package, your Build folder is replaced. _WorldWideWeb_ refreshes its browser whenever its site contents are changed. More details can be found [here](https://iconfactory.com/worldwideweb/). 

I purchased the iOS version of _WorldWideWeb_ (_WorldWideWeb - mobile_) and found it very useful for testing a website on my iPhone. Unfortunately, you cannot get _WorldWideWeb - mobile_ to run on a Silicon Mac; you have to buy desktop and mobile versions separately; that said, the £9.99 charged for each version is a one off lifetime purchase with no subscriptions. To my mind it's good value!

**Comment by JPToroDev** [comment]
It appears this issue has been resolved. If not, feel free to open another issue or submit a PR.
