### ISSUE TITLE
How to make a whole card or image as a link?

### ISSUE THREAD

**Issue by Haibo-Zhou** [twostraws/Ignite#99]
I dig around ignite yesterday, and decide to replace my personal website with it. How to make a whole card or an image as a link? Below is my current achieved, I want to make a HStack to represent my apps in AppStore, and hit each of app image, it goes to relatived app intro page.

<img width="792" alt="Screenshot 2024-07-26 at 09 49 53" src="https://github.com/user-attachments/assets/22ddc04f-0168-4275-9498-263620366af8">

```
    Section {
            Card {
                Image(decorative: "/images/products/movie-fans/movie-fans-logo.png")
                    .resizable()
                    .cornerRadius(24)
                Spacer()
                Link("Movie Fans", target: "/products/ohmusic/oh-music-privacy-policy")
                    .linkStyle(.button)
                    .role(.primary)
            }
            .frame(maxWidth: 200)
            .role(.light)
            .cardStyle(.solid)
            .horizontalAlignment(.center)
            
            Card {
                Image(decorative: "/images/products/movie-fans/movie-fans-logo.png")
                    .resizable()
                    .cornerRadius(24)
                Spacer()
                Link("Movie Fans", target: "/products/ohmusic/oh-music-privacy-policy")
                    .linkStyle(.button)
                    .role(.primary)
            }
            .frame(maxWidth: 200)
            .role(.light)
            .cardStyle(.solid)
            .horizontalAlignment(.center)
            
            
            Card {
                Image(decorative: "/images/products/oh-music/oh-music-logo.png")
                    .resizable()
                    .cornerRadius(24)
                Spacer()
                Link("Oh Music", target: "/products/ohmusic/oh-music-privacy-policy")
                    .linkStyle(.button)
                    .role(.dark)
            }
            .frame(maxWidth: 200)
            .role(.light)
            .cardStyle(.solid)
            .horizontalAlignment(.center)
            
            Spacer(size: .extraLarge)
            Spacer(size: .extraLarge)
            Spacer(size: .extraLarge)
        }
```

**Comment by markstamer** [comment]
Hi @Haibo-Zhou, I see you struggle here. Link only supports `InlineElement` not `PageElement`.  For now you could try to use the `onClick` modifier in combination with a `CustomAction`. Also to achieve a pointer when hovering over the card try if you can use the style `cursor: pointer;`. In summary, see if something like this works: 

```swift
Card {
    ...
} 
.style("cursor: pointer")
.onClick(CustomAction(""window.location.href='https://www.example.com';")
```

**Comment by vdhamer** [comment]
> Hi @Haibo-Zhou, I see you struggle here. Link only supports `InlineElement` not `PageElement`. For now you could try to use the `onClick` modifier in combination with a `CustomAction`. Also to achieve a pointer when hovering over the card try if you can use the style `cursor: pointer;`. In summary, see if something like this works:
> 
> ```swift
> Card {
>     ...
> } 
> .style("cursor: pointer")
> .onClick(CustomAction(""window.location.href='https://www.example.com';")
> ```

This works (at least I tried it on an Image):
```
                .style("cursor: pointer")
                .onClick {
                    CustomAction("window.location.href=\"https://www.example.com\";")
                }
```

**Comment by JPToroDev** [comment]
In the recent updates, a link can now be added to any view.
